const Assessment = require('../models/Assessment');

const SITE_URL = 'https://nursfpx4015.com';

// ── XSLT Stylesheets ────────────────────────────────────────────────

const INDEX_XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html lang="en">
<head>
  <title>XML Sitemap Index</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #333; max-width: 900px; margin: 0 auto; padding: 30px 20px; }
    h1 { font-size: 24px; font-weight: 700; margin-bottom: 6px; }
    p { color: #666; font-size: 14px; margin-bottom: 20px; }
    p a { color: #05809e; text-decoration: none; border-bottom: 1px solid #cde; }
    p a:hover { color: #024; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { text-align: left; padding: 10px 12px; background: #f7f7f7; border-bottom: 2px solid #ddd; font-weight: 600; color: #555; }
    td { padding: 10px 12px; border-bottom: 1px solid #eee; }
    tr:hover td { background: #fcfcfc; }
    td a { color: #05809e; text-decoration: none; }
    td a:hover { text-decoration: underline; }
    .count { color: #888; font-size: 13px; margin-bottom: 24px; }
  </style>
</head>
<body>
  <h1>XML Sitemap</h1>
  <p>Generated by <strong>NURSFPX4015</strong> — this is an XML Sitemap, meant for consumption by search engines.</p>
  <p>You can find more information about XML sitemaps on <a href="https://www.sitemaps.org/" target="_blank">sitemaps.org</a>.</p>
  <p class="count">This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.</p>
  <table>
    <tr><th>Sitemap</th><th>Last Modified</th></tr>
    <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
      <tr>
        <td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
        <td><xsl:value-of select="sitemap:lastmod"/></td>
      </tr>
    </xsl:for-each>
  </table>
</body>
</html>
</xsl:template>
</xsl:stylesheet>`;

const URLSET_XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html lang="en">
<head>
  <title>XML Sitemap</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #333; max-width: 900px; margin: 0 auto; padding: 30px 20px; }
    h1 { font-size: 24px; font-weight: 700; margin-bottom: 6px; }
    p { color: #666; font-size: 14px; margin-bottom: 20px; }
    p a { color: #05809e; text-decoration: none; border-bottom: 1px solid #cde; }
    p a:hover { color: #024; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { text-align: left; padding: 10px 12px; background: #f7f7f7; border-bottom: 2px solid #ddd; font-weight: 600; color: #555; }
    td { padding: 10px 12px; border-bottom: 1px solid #eee; }
    tr:hover td { background: #fcfcfc; }
    td a { color: #05809e; text-decoration: none; }
    td a:hover { text-decoration: underline; }
    .count { color: #888; font-size: 13px; margin-bottom: 24px; }
  </style>
</head>
<body>
  <h1>XML Sitemap</h1>
  <p>Generated by <strong>NURSFPX4015</strong> — this is an XML Sitemap, meant for consumption by search engines.</p>
  <p>You can find more information about XML sitemaps on <a href="https://www.sitemaps.org/" target="_blank">sitemaps.org</a>.</p>
  <p class="count">This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</p>
  <table>
    <tr><th>URL</th><th>Last Modified</th></tr>
    <xsl:for-each select="sitemap:urlset/sitemap:url">
      <tr>
        <td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
        <td><xsl:value-of select="sitemap:lastmod"/></td>
      </tr>
    </xsl:for-each>
  </table>
</body>
</html>
</xsl:template>
</xsl:stylesheet>`;

// ── Helpers ──────────────────────────────────────────────────────────

const sendXml = (res, xml) => {
  res.set('Content-Type', 'application/xml; charset=UTF-8');
  res.set('Cache-Control', 'public, max-age=3600');
  res.send(xml);
};

const today = () => new Date().toISOString().replace(/T.*/, '');

const toISO = (d) => (d ? new Date(d).toISOString() : new Date().toISOString());

// ── XSLT stylesheet handlers ────────────────────────────────────────

const indexXsl = (_req, res) => {
  res.set('Content-Type', 'application/xml; charset=UTF-8');
  res.send(INDEX_XSL);
};

const urlsetXsl = (_req, res) => {
  res.set('Content-Type', 'application/xml; charset=UTF-8');
  res.send(URLSET_XSL);
};

// ── Sitemap Index (/sitemap.xml) ─────────────────────────────────────

const STATIC_PAGES = [
  { loc: '/' },
  { loc: '/about' },
  { loc: '/contact' },
  { loc: '/reviews' },
  { loc: '/free-samples' },
];

const index = async (_req, res) => {
  try {
    const assessments = await Assessment.find(
      { slug: { $exists: true, $ne: '' } },
      { updatedAt: 1 }
    ).sort({ updatedAt: -1 }).limit(1).lean();

    const postLastMod = assessments.length ? toISO(assessments[0].updatedAt) : new Date().toISOString();
    const pageLastMod = new Date().toISOString();

    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += '<?xml-stylesheet type="text/xsl" href="/sitemap-index.xsl"?>\n';
    xml += '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

    xml += '  <sitemap>\n';
    xml += `    <loc>${SITE_URL}/page-sitemap.xml</loc>\n`;
    xml += `    <lastmod>${pageLastMod}</lastmod>\n`;
    xml += '  </sitemap>\n';

    xml += '  <sitemap>\n';
    xml += `    <loc>${SITE_URL}/post-sitemap.xml</loc>\n`;
    xml += `    <lastmod>${postLastMod}</lastmod>\n`;
    xml += '  </sitemap>\n';

    xml += '</sitemapindex>';
    sendXml(res, xml);
  } catch (error) {
    console.error('Sitemap index error:', error);
    res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></sitemapindex>');
  }
};

// ── Page Sitemap (/page-sitemap.xml) ─────────────────────────────────

const pages = (_req, res) => {
  const d = today();
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<?xml-stylesheet type="text/xsl" href="/sitemap-urlset.xsl"?>\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

  for (const page of STATIC_PAGES) {
    xml += '  <url>\n';
    xml += `    <loc>${SITE_URL}${page.loc}</loc>\n`;
    xml += `    <lastmod>${d}</lastmod>\n`;
    xml += '  </url>\n';
  }

  xml += '</urlset>';
  sendXml(res, xml);
};

// ── Post / Assessment Sitemap (/post-sitemap.xml) ────────────────────

const posts = async (_req, res) => {
  try {
    const assessments = await Assessment.find(
      { slug: { $exists: true, $ne: '' } },
      { slug: 1, updatedAt: 1 }
    ).sort({ updatedAt: -1 }).lean();

    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += '<?xml-stylesheet type="text/xsl" href="/sitemap-urlset.xsl"?>\n';
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

    for (const a of assessments) {
      const lastmod = a.updatedAt ? new Date(a.updatedAt).toISOString().replace(/T.*/, '') : today();
      xml += '  <url>\n';
      xml += `    <loc>${SITE_URL}/${encodeURIComponent(a.slug)}</loc>\n`;
      xml += `    <lastmod>${lastmod}</lastmod>\n`;
      xml += '  </url>\n';
    }

    xml += '</urlset>';
    sendXml(res, xml);
  } catch (error) {
    console.error('Post sitemap error:', error);
    res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>');
  }
};

module.exports = { index, pages, posts, indexXsl, urlsetXsl };
